require('dotenv').config();
const fetch = require('node-fetch');
const fs = require('fs');
const path = require('path');

// --- Config ---
const WALLET = process.env.TALENT_WALLET || 'unknown';
const API_KEY = process.env.OPENAI_API_KEY;
const REPORTS_DIR = path.join(__dirname, 'reports');

// Fallback list of 5 free models on OpenRouter
const MODELS = [
  'openrouter/auto',
  'meta-llama/llama-3.3-70b:free',
  'deepseek/deepseek-r1-distill:free',
  'google/gemini-2.0-flash-exp:free',
  'qwen/qwen3-8b:free'
];

// --- Base ecosystem topics for variety ---
const TOPICS = [
  'Base L2 TVL trends and top DeFi protocols',
  'New smart contract deployments on Base network this week',
  'Base ecosystem NFT activity and notable collections',
  'AI agent projects building on Base blockchain',
  'Base network gas fees and transaction volume analysis',
  'Coinbase and Base ecosystem developer activity',
  'Cross-chain bridges activity to and from Base',
  'Base ecosystem stablecoin flows and liquidity'
];

async function callOpenRouter(prompt, modelIndex = 0) {
  if (modelIndex >= MODELS.length) {
    throw new Error('All models failed');
  }
  const model = MODELS[modelIndex];
  console.log(`Trying model: ${model}`);

  try {
    const res = await fetch('https://openrouter.ai/api/v1/chat/completions', {
      method: 'POST',
      headers: {
        'Authorization': `Bearer ${API_KEY}`,
        'Content-Type': 'application/json',
        'HTTP-Referer': 'https://github.com/base-pulse',
        'X-Title': 'BasePulse'
      },
      body: JSON.stringify({
        model: model,
        messages: [{ role: 'user', content: prompt }],
        max_tokens: 900
      })
    });

    if (!res.ok) {
      throw new Error(`HTTP ${res.status}`);
    }

    const data = await res.json();
    if (!data.choices || !data.choices[0]) {
      throw new Error('Empty response');
    }
    console.log(`Success with model: ${model}`);
    return { text: data.choices[0].message.content, model };
  } catch (err) {
    console.warn(`Model ${model} failed: ${err.message}. Trying next...`);
    return callOpenRouter(prompt, modelIndex + 1);
  }
}

async function generateReport() {
  const now = new Date();
  const dateStr = now.toISOString().split('T')[0];
  const topic = TOPICS[Math.floor(Math.random() * TOPICS.length)];

  const prompt = `You are a Web3 analyst specializing in the Base blockchain ecosystem.
Write a concise daily digest report about: "${topic}"

Format the report in Markdown with these sections:
## 📊 Overview
(2-3 sentences summary)

## 🔍 Key Insights
(3-5 bullet points with specific observations)

## 🤖 AI Analysis
(2-3 sentences of analytical commentary)

## 📈 What to Watch
(2 bullet points of things to monitor)

---
*Generated by BasePulse — AI digest for the Base ecosystem*
*Wallet: ${WALLET}*
*Date: ${dateStr}*

Keep it professional, data-driven, and useful for Base ecosystem participants.`;

  console.log(`Generating report for topic: ${topic}`);
  const { text, model } = await callOpenRouter(prompt);

  // Save report
  if (!fs.existsSync(REPORTS_DIR)) {
    fs.mkdirSync(REPORTS_DIR, { recursive: true });
  }

  const timestamp = now.toISOString().replace(/[:.]/g, '-');
  const filename = `report-${dateStr}-${timestamp}.md`;
  const filepath = path.join(REPORTS_DIR, filename);

  const fullReport = `# BasePulse Daily Report\n\n**Topic:** ${topic}\n**Model used:** ${model}\n\n${text}\n`;
  fs.writeFileSync(filepath, fullReport);
  console.log(`Report saved: ${filepath}`);

  // Update index
  const indexPath = path.join(REPORTS_DIR, 'README.md');
  const indexLine = `- [${dateStr} — ${topic}](./${filename})\n`;
  fs.appendFileSync(indexPath, indexLine);
  console.log('Index updated');

  return filename;
}

// Main
(async () => {
  console.log('BasePulse starting...');
  console.log(`Wallet: ${WALLET}`);
  try {
    const file = await generateReport();
    console.log(`Done! Report: ${file}`);
  } catch (err) {
    console.error('Fatal error:', err.message);
    process.exit(1);
  }
})();
